name: fxbo
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  global_configuration:
  dio:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/closeIcon.png
    - assets/plusIcon.png
    - assets/plusButton.png
    - assets/messageIcon.png
    - assets/depositIcon.png
    - assets/uploadIcon.png
    - assets/passwordIcon.png
    - assets/emailIcon.png
    - assets/logo.png
    - assets/cfg/

  fonts:
    - family: Montserrat
      fonts:
      - asset: assets/montserrat.ttf
    - family: Poppins
      fonts:
      - asset: assets/poppins.ttf
    - family: Nunito
      fonts:
      - asset: assets/nunito.ttf
    - family: Nunito-Bold
      fonts:
      - asset: assets/nunito-bold.ttf