name: fxbo
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio:
  shared_preferences:
  injectable:
  get_it:
  provider:
  dotted_border:

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat.ttf
    - family: Poppins
      fonts:
        - asset: fonts/poppins.ttf
    - family: Nunito
      fonts:
        - asset: fonts/nunito.ttf
    - family: NunitoBold
      fonts:
        - asset: fonts/nunito_bold.ttf

flutter_intl:
  enabled: true