name: fxbo
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dio:
  shared_preferences:
  injectable:
  get_it:
  provider:
  dotted_border: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
      - asset: assets/montserrat.ttf
    - family: Poppins
      fonts:
      - asset: assets/poppins.ttf
    - family: Nunito
      fonts:
      - asset: assets/nunito.ttf
    - family: Nunito-Bold
      fonts:
      - asset: assets/nunito-bold.ttf