name: fxbo
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  global_configuration:
  dio:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/cfg/

  fonts:
    - family: Montserrat
      fonts:
      - asset: assets/montserrat.ttf
    - family: Poppins
      fonts:
      - asset: assets/poppins.ttf
    - family: Nunito
      fonts:
      - asset: assets/nunito.ttf
    - family: Nunito-Bold
      fonts:
      - asset: assets/nunito-bold.ttf